site_name: BU Bioinformatics

nav:
    - Home: index.md
    - SCC: SCC.md
    - Jupyter: Jupyter.md
    - Bioinformatics Libraries: Bioinformatics_libs.md
    - BU Pipelines: BU_pipelines.md
    - Microbiome: Microbiome.md
    
 
    
theme:
    name: readthedocs
    highlightjs: true
    hljs_languages:
        - python
        - r


markdown_extensions:
  - attr_list
  - md_in_html

